resources:
  - https_transformation.yaml
  - netty-backend.yaml
patches:
- path: deployment-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: https-transform-deployment
