name: notification_update

on:
  workflow_dispatch:
  push:
      branches:
          - 'main'
      paths:
          - 'notifications/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Ballerina Build
      uses: ballerina-platform/ballerina-action@master
      env:
        DOCKER_BUILDKIT: 0
        WORKING_DIR: notifications
      with:
        args:
          build
    - name: Docker push
      run: |
        docker images
        docker push ballerina/chat_notifications:latest
